INSERT INTO books (id, isbn, title, author) VALUES (1, '9788900000001', '스프링 부트 실전 가이드 Vol.1', '저자_Alpha1');
INSERT INTO books (id, isbn, title, author) VALUES (2, '9788900000002', '스프링 부트 실전 가이드 Vol.2', '저자_Alpha2');
INSERT INTO books (id, isbn, title, author) VALUES (3, '9788900000003', '스프링 부트 실전 가이드 Vol.3', '저자_Alpha3');
INSERT INTO books (id, isbn, title, author) VALUES (4, '9788900000004', '스프링 부트 실전 가이드 Vol.4', '저자_Alpha4');
INSERT INTO books (id, isbn, title, author) VALUES (5, '9788900000005', '스프링 부트 실전 가이드 Vol.5', '저자_Alpha5');
INSERT INTO books (id, isbn, title, author) VALUES (6, '9788900000006', '스프링 부트 실전 가이드 Vol.6', '저자_Alpha6');
INSERT INTO books (id, isbn, title, author) VALUES (7, '9788900000007', '스프링 부트 실전 가이드 Vol.7', '저자_Alpha7');
INSERT INTO books (id, isbn, title, author) VALUES (8, '9788900000008', '스프링 부트 실전 가이드 Vol.8', '저자_Alpha8');
INSERT INTO books (id, isbn, title, author) VALUES (9, '9788900000009', '스프링 부트 실전 가이드 Vol.9', '저자_Alpha9');
INSERT INTO books (id, isbn, title, author) VALUES (10, '9788900000010', '스프링 부트 실전 가이드 Vol.10', '저자_Alpha10');
INSERT INTO books (id, isbn, title, author) VALUES (11, '9788900000011', '스프링 부트 실전 가이드 Vol.11', '저자_Alpha11');
INSERT INTO books (id, isbn, title, author) VALUES (12, '9788900000012', '스프링 부트 실전 가이드 Vol.12', '저자_Alpha12');
INSERT INTO books (id, isbn, title, author) VALUES (13, '9788900000013', '스프링 부트 실전 가이드 Vol.13', '저자_Alpha13');
INSERT INTO books (id, isbn, title, author) VALUES (14, '9788900000014', '스프링 부트 실전 가이드 Vol.14', '저자_Alpha14');
INSERT INTO books (id, isbn, title, author) VALUES (15, '9788900000015', '스프링 부트 실전 가이드 Vol.15', '저자_Alpha15');
INSERT INTO books (id, isbn, title, author) VALUES (16, '9788900000016', '스프링 부트 실전 가이드 Vol.16', '저자_Alpha16');
INSERT INTO books (id, isbn, title, author) VALUES (17, '9788900000017', '스프링 부트 실전 가이드 Vol.17', '저자_Alpha17');
INSERT INTO books (id, isbn, title, author) VALUES (18, '9788900000018', '스프링 부트 실전 가이드 Vol.18', '저자_Alpha18');
INSERT INTO books (id, isbn, title, author) VALUES (19, '9788900000019', '스프링 부트 실전 가이드 Vol.19', '저자_Alpha19');
INSERT INTO books (id, isbn, title, author) VALUES (20, '9788900000020', '스프링 부트 실전 가이드 Vol.20', '저자_Alpha20');
INSERT INTO books (id, isbn, title, author) VALUES (21, '9788900000021', '스프링 부트 실전 가이드 Vol.21', '저자_Alpha21');
INSERT INTO books (id, isbn, title, author) VALUES (22, '9788900000022', '스프링 부트 실전 가이드 Vol.22', '저자_Alpha22');
INSERT INTO books (id, isbn, title, author) VALUES (23, '9788900000023', '스프링 부트 실전 가이드 Vol.23', '저자_Alpha23');
INSERT INTO books (id, isbn, title, author) VALUES (24, '9788900000024', '스프링 부트 실전 가이드 Vol.24', '저자_Alpha24');
INSERT INTO books (id, isbn, title, author) VALUES (25, '9788900000025', '스프링 부트 실전 가이드 Vol.25', '저자_Alpha25');
INSERT INTO books (id, isbn, title, author) VALUES (26, '9788900000026', '스프링 부트 실전 가이드 Vol.26', '저자_Alpha26');
INSERT INTO books (id, isbn, title, author) VALUES (27, '9788900000027', '스프링 부트 실전 가이드 Vol.27', '저자_Alpha27');
INSERT INTO books (id, isbn, title, author) VALUES (28, '9788900000028', '스프링 부트 실전 가이드 Vol.28', '저자_Alpha28');
INSERT INTO books (id, isbn, title, author) VALUES (29, '9788900000029', '스프링 부트 실전 가이드 Vol.29', '저자_Alpha29');
INSERT INTO books (id, isbn, title, author) VALUES (30, '9788900000030', '스프링 부트 실전 가이드 Vol.30', '저자_Alpha30');
INSERT INTO books (id, isbn, title, author) VALUES (31, '9788900000031', '스프링 부트 실전 가이드 Vol.31', '저자_Alpha31');
INSERT INTO books (id, isbn, title, author) VALUES (32, '9788900000032', '스프링 부트 실전 가이드 Vol.32', '저자_Alpha32');
INSERT INTO books (id, isbn, title, author) VALUES (33, '9788900000033', '스프링 부트 실전 가이드 Vol.33', '저자_Alpha33');
INSERT INTO books (id, isbn, title, author) VALUES (34, '9788900000034', '스프링 부트 실전 가이드 Vol.34', '저자_Alpha34');
INSERT INTO books (id, isbn, title, author) VALUES (35, '9788900000035', '스프링 부트 실전 가이드 Vol.35', '저자_Alpha35');
INSERT INTO books (id, isbn, title, author) VALUES (36, '9788900000036', '스프링 부트 실전 가이드 Vol.36', '저자_Alpha36');
INSERT INTO books (id, isbn, title, author) VALUES (37, '9788900000037', '스프링 부트 실전 가이드 Vol.37', '저자_Alpha37');
INSERT INTO books (id, isbn, title, author) VALUES (38, '9788900000038', '스프링 부트 실전 가이드 Vol.38', '저자_Alpha38');
INSERT INTO books (id, isbn, title, author) VALUES (39, '9788900000039', '스프링 부트 실전 가이드 Vol.39', '저자_Alpha39');
INSERT INTO books (id, isbn, title, author) VALUES (40, '9788900000040', '스프링 부트 실전 가이드 Vol.40', '저자_Alpha40');
INSERT INTO books (id, isbn, title, author) VALUES (41, '9788900000041', '스프링 부트 실전 가이드 Vol.41', '저자_Alpha41');
INSERT INTO books (id, isbn, title, author) VALUES (42, '9788900000042', '스프링 부트 실전 가이드 Vol.42', '저자_Alpha42');
INSERT INTO books (id, isbn, title, author) VALUES (43, '9788900000043', '스프링 부트 실전 가이드 Vol.43', '저자_Alpha43');
INSERT INTO books (id, isbn, title, author) VALUES (44, '9788900000044', '스프링 부트 실전 가이드 Vol.44', '저자_Alpha44');
INSERT INTO books (id, isbn, title, author) VALUES (45, '9788900000045', '스프링 부전 가이드 Vol.45', '저자_Alpha45');
INSERT INTO books (id, isbn, title, author) VALUES (46, '9788900000046', '스프링 부트 실전 가이드 Vol.46', '저자_Alpha46');
INSERT INTO books (id, isbn, title, author) VALUES (47, '9788900000047', '스프링 부트 실전 가이드 Vol.47', '저자_Alpha47');
INSERT INTO books (id, isbn, title, author) VALUES (48, '9788900000048', '스프링 부트 실전 가이드 Vol.48', '저자_Alpha48');
INSERT INTO books (id, isbn, title, author) VALUES (49, '9788900000049', '스프링 부트 실전 가이드 Vol.49', '저자_Alpha49');
INSERT INTO books (id, isbn, title, author) VALUES (50, '9788900000050', '스프링 부트 실전 가이드 Vol.50', '저자_Alpha50');

INSERT INTO book_copies (id, status, book_id) VALUES (1, 'AVAILABLE', 1);
INSERT INTO book_copies (id, status, book_id) VALUES (2, 'AVAILABLE', 1);
INSERT INTO book_copies (id, status, book_id) VALUES (3, 'BORROWED', 1);
INSERT INTO book_copies (id, status, book_id) VALUES (4, 'AVAILABLE', 1);
INSERT INTO book_copies (id, status, book_id) VALUES (5, 'AVAILABLE', 2);
INSERT INTO book_copies (id, status, book_id) VALUES (6, 'AVAILABLE', 2);
INSERT INTO book_copies (id, status, book_id) VALUES (7, 'BORROWED', 2);
INSERT INTO book_copies (id, status, book_id) VALUES (8, 'AVAILABLE', 2);
INSERT INTO book_copies (id, status, book_id) VALUES (9, 'AVAILABLE', 3);
INSERT INTO book_copies (id, status, book_id) VALUES (10, 'AVAILABLE', 3);
INSERT INTO book_copies (id, status, book_id) VALUES (11, 'BORROWED', 3);
INSERT INTO book_copies (id, status, book_id) VALUES (12, 'AVAILABLE', 3);
INSERT INTO book_copies (id, status, book_id) VALUES (13, 'AVAILABLE', 4);
INSERT INTO book_copies (id, status, book_id) VALUES (14, 'AVAILABLE', 4);
INSERT INTO book_copies (id, status, book_id) VALUES (15, 'BORROWED', 4);
INSERT INTO book_copies (id, status, book_id) VALUES (16, 'AVAILABLE', 4);
INSERT INTO book_copies (id, status, book_id) VALUES (17, 'AVAILABLE', 5);
INSERT INTO book_copies (id, status, book_id) VALUES (18, 'AVAILABLE', 5);
INSERT INTO book_copies (id, status, book_id) VALUES (19, 'BORROWED', 5);
INSERT INTO book_copies (id, status, book_id) VALUES (20, 'AVAILABLE', 5);
INSERT INTO book_copies (id, status, book_id) VALUES (21, 'AVAILABLE', 6);
INSERT INTO book_copies (id, status, book_id) VALUES (22, 'AVAILABLE', 6);
INSERT INTO book_copies (id, status, book_id) VALUES (23, 'BORROWED', 6);
INSERT INTO book_copies (id, status, book_id) VALUES (24, 'AVAILABLE', 6);
INSERT INTO book_copies (id, status, book_id) VALUES (25, 'AVAILABLE', 7);
INSERT INTO book_copies (id, status, book_id) VALUES (26, 'AVAILABLE', 7);
INSERT INTO book_copies (id, status, book_id) VALUES (27, 'BORROWED', 7);
INSERT INTO book_copies (id, status, book_id) VALUES (28, 'AVAILABLE', 7);
INSERT INTO book_copies (id, status, book_id) VALUES (29, 'AVAILABLE', 8);
INSERT INTO book_copies (id, status, book_id) VALUES (30, 'AVAILABLE', 8);
INSERT INTO book_copies (id, status, book_id) VALUES (31, 'BORROWED', 8);
INSERT INTO book_copies (id, status, book_id) VALUES (32, 'AVAILABLE', 8);
INSERT INTO book_copies (id, status, book_id) VALUES (33, 'AVAILABLE', 9);
INSERT INTO book_copies (id, status, book_id) VALUES (34, 'AVAILABLE', 9);
INSERT INTO book_copies (id, status, book_id) VALUES (35, 'BORROWED', 9);
INSERT INTO book_copies (id, status, book_id) VALUES (36, 'AVAILABLE', 9);
INSERT INTO book_copies (id, status, book_id) VALUES (37, 'AVAILABLE', 10);
INSERT INTO book_copies (id, status, book_id) VALUES (38, 'AVAILABLE', 10);
INSERT INTO book_copies (id, status, book_id) VALUES (39, 'BORROWED', 10);
INSERT INTO book_copies (id, status, book_id) VALUES (40, 'AVAILABLE', 10);
INSERT INTO book_copies (id, status, book_id) VALUES (41, 'AVAILABLE', 11);
INSERT INTO book_copies (id, status, book_id) VALUES (42, 'AVAILABLE', 11);
INSERT INTO book_copies (id, status, book_id) VALUES (43, 'BORROWED', 11);
INSERT INTO book_copies (id, status, book_id) VALUES (44, 'AVAILABLE', 11);
INSERT INTO book_copies (id, status, book_id) VALUES (45, 'AVAILABLE', 12);
INSERT INTO book_copies (id, status, book_id) VALUES (46, 'AVAILABLE', 12);
INSERT INTO book_copies (id, status, book_id) VALUES (47, 'BORROWED', 12);
INSERT INTO book_copies (id, status, book_id) VALUES (48, 'AVAILABLE', 12);
INSERT INTO book_copies (id, status, book_id) VALUES (49, 'AVAILABLE', 13);
INSERT INTO book_copies (id, status, book_id) VALUES (50, 'AVAILABLE', 13);
INSERT INTO book_copies (id, status, book_id) VALUES (51, 'BORROWED', 13);
INSERT INTO book_copies (id, status, book_id) VALUES (52, 'AVAILABLE', 13);
INSERT INTO book_copies (id, status, book_id) VALUES (53, 'AVAILABLE', 14);
INSERT INTO book_copies (id, status, book_id) VALUES (54, 'AVAILABLE', 14);
INSERT INTO book_copies (id, status, book_id) VALUES (55, 'BORROWED', 14);
INSERT INTO book_copies (id, status, book_id) VALUES (56, 'AVAILABLE', 14);
INSERT INTO book_copies (id, status, book_id) VALUES (57, 'AVAILABLE', 15);
INSERT INTO book_copies (id, status, book_id) VALUES (58, 'AVAILABLE', 15);
INSERT INTO book_copies (id, status, book_id) VALUES (59, 'BORROWED', 15);
INSERT INTO book_copies (id, status, book_id) VALUES (60, 'AVAILABLE', 15);
INSERT INTO book_copies (id, status, book_id) VALUES (61, 'AVAILABLE', 16);
INSERT INTO book_copies (id, status, book_id) VALUES (62, 'AVAILABLE', 16);
INSERT INTO book_copies (id, status, book_id) VALUES (63, 'BORROWED', 16);
INSERT INTO book_copies (id, status, book_id) VALUES (64, 'AVAILABLE', 16);
INSERT INTO book_copies (id, status, book_id) VALUES (65, 'AVAILABLE', 17);
INSERT INTO book_copies (id, status, book_id) VALUES (66, 'AVAILABLE', 17);
INSERT INTO book_copies (id, status, book_id) VALUES (67, 'BORROWED', 17);
INSERT INTO book_copies (id, status, book_id) VALUES (68, 'AVAILABLE', 17);
INSERT INTO book_copies (id, status, book_id) VALUES (69, 'AVAILABLE', 18);
INSERT INTO book_copies (id, status, book_id) VALUES (70, 'AVAILABLE', 18);
INSERT INTO book_copies (id, status, book_id) VALUES (71, 'BORROWED', 18);
INSERT INTO book_copies (id, status, book_id) VALUES (72, 'AVAILABLE', 18);
INSERT INTO book_copies (id, status, book_id) VALUES (73, 'AVAILABLE', 19);
INSERT INTO book_copies (id, status, book_id) VALUES (74, 'AVAILABLE', 19);
INSERT INTO book_copies (id, status, book_id) VALUES (75, 'BORROWED', 19);
INSERT INTO book_copies (id, status, book_id) VALUES (76, 'AVAILABLE', 19);
INSERT INTO book_copies (id, status, book_id) VALUES (77, 'AVAILABLE', 20);
INSERT INTO book_copies (id, status, book_id) VALUES (78, 'AVAILABLE', 20);
INSERT INTO book_copies (id, status, book_id) VALUES (79, 'BORROWED', 20);
INSERT INTO book_copies (id, status, book_id) VALUES (80, 'AVAILABLE', 20);
INSERT INTO book_copies (id, status, book_id) VALUES (81, 'AVAILABLE', 21);
INSERT INTO book_copies (id, status, book_id) VALUES (82, 'AVAILABLE', 21);
INSERT INTO book_copies (id, status, book_id) VALUES (83, 'BORROWED', 21);
INSERT INTO book_copies (id, status, book_id) VALUES (84, 'AVAILABLE', 21);
INSERT INTO book_copies (id, status, book_id) VALUES (85, 'AVAILABLE', 22);
INSERT INTO book_copies (id, status, book_id) VALUES (86, 'AVAILABLE', 22);
INSERT INTO book_copies (id, status, book_id) VALUES (87, 'BORROWED', 22);
INSERT INTO book_copies (id, status, book_id) VALUES (88, 'AVAILABLE', 22);
INSERT INTO book_copies (id, status, book_id) VALUES (89, 'AVAILABLE', 23);
INSERT INTO book_copies (id, status, book_id) VALUES (90, 'AVAILABLE', 23);
INSERT INTO book_copies (id, status, book_id) VALUES (91, 'BORROWED', 23);
INSERT INTO book_copies (id, status, book_id) VALUES (92, 'AVAILABLE', 23);
INSERT INTO book_copies (id, status, book_id) VALUES (93, 'AVAILABLE', 24);
INSERT INTO book_copies (id, status, book_id) VALUES (94, 'AVAILABLE', 24);
INSERT INTO book_copies (id, status, book_id) VALUES (95, 'BORROWED', 24);
INSERT INTO book_copies (id, status, book_id) VALUES (96, 'AVAILABLE', 24);
INSERT INTO book_copies (id, status, book_id) VALUES (97, 'AVAILABLE', 25);
INSERT INTO book_copies (id, status, book_id) VALUES (98, 'AVAILABLE', 25);
INSERT INTO book_copies (id, status, book_id) VALUES (99, 'BORROWED', 25);
INSERT INTO book_copies (id, status, book_id) VALUES (100, 'AVAILABLE', 25);
INSERT INTO book_copies (id, status, book_id) VALUES (101, 'AVAILABLE', 26);
INSERT INTO book_copies (id, status, book_id) VALUES (102, 'AVAILABLE', 26);
INSERT INTO book_copies (id, status, book_id) VALUES (103, 'BORROWED', 26);
INSERT INTO book_copies (id, status, book_id) VALUES (104, 'AVAILABLE', 26);
INSERT INTO book_copies (id, status, book_id) VALUES (105, 'AVAILABLE', 27);
INSERT INTO book_copies (id, status, book_id) VALUES (106, 'AVAILABLE', 27);
INSERT INTO book_copies (id, status, book_id) VALUES (107, 'BORROWED', 27);
INSERT INTO book_copies (id, status, book_id) VALUES (108, 'AVAILABLE', 27);
INSERT INTO book_copies (id, status, book_id) VALUES (109, 'AVAILABLE', 28);
INSERT INTO book_copies (id, status, book_id) VALUES (110, 'AVAILABLE', 28);
INSERT INTO book_copies (id, status, book_id) VALUES (111, 'BORROWED', 28);
INSERT INTO book_copies (id, status, book_id) VALUES (112, 'AVAILABLE', 28);
INSERT INTO book_copies (id, status, book_id) VALUES (113, 'AVAILABLE', 29);
INSERT INTO book_copies (id, status, book_id) VALUES (114, 'AVAILABLE', 29);
INSERT INTO book_copies (id, status, book_id) VALUES (115, 'BORROWED', 29);
INSERT INTO book_copies (id, status, book_id) VALUES (116, 'AVAILABLE', 29);
INSERT INTO book_copies (id, status, book_id) VALUES (117, 'AVAILABLE', 30);
INSERT INTO book_copies (id, status, book_id) VALUES (118, 'AVAILABLE', 30);
INSERT INTO book_copies (id, status, book_id) VALUES (119, 'BORROWED', 30);
INSERT INTO book_copies (id, status, book_id) VALUES (120, 'AVAILABLE', 30);
INSERT INTO book_copies (id, status, book_id) VALUES (121, 'AVAILABLE', 31);
INSERT INTO book_copies (id, status, book_id) VALUES (122, 'AVAILABLE', 31);
INSERT INTO book_copies (id, status, book_id) VALUES (123, 'BORROWED', 31);
INSERT INTO book_copies (id, status, book_id) VALUES (124, 'AVAILABLE', 31);
INSERT INTO book_copies (id, status, book_id) VALUES (125, 'AVAILABLE', 32);
INSERT INTO book_copies (id, status, book_id) VALUES (126, 'AVAILABLE', 32);
INSERT INTO book_copies (id, status, book_id) VALUES (127, 'BORROWED', 32);
INSERT INTO book_copies (id, status, book_id) VALUES (128, 'AVAILABLE', 32);
INSERT INTO book_copies (id, status, book_id) VALUES (129, 'AVAILABLE', 33);
INSERT INTO book_copies (id, status, book_id) VALUES (130, 'AVAILABLE', 33);
INSERT INTO book_copies (id, status, book_id) VALUES (131, 'BORROWED', 33);
INSERT INTO book_copies (id, status, book_id) VALUES (132, 'AVAILABLE', 33);
INSERT INTO book_copies (id, status, book_id) VALUES (133, 'AVAILABLE', 34);
INSERT INTO book_copies (id, status, book_id) VALUES (134, 'AVAILABLE', 34);
INSERT INTO book_copies (id, status, book_id) VALUES (135, 'BORROWED', 34);
INSERT INTO book_copies (id, status, book_id) VALUES (136, 'AVAILABLE', 34);
INSERT INTO book_copies (id, status, book_id) VALUES (137, 'AVAILABLE', 35);
INSERT INTO book_copies (id, status, book_id) VALUES (138, 'AVAILABLE', 35);
INSERT INTO book_copies (id, status, book_id) VALUES (139, 'BORROWED', 35);
INSERT INTO book_copies (id, status, book_id) VALUES (140, 'AVAILABLE', 35);
INSERT INTO book_copies (id, status, book_id) VALUES (141, 'AVAILABLE', 36);
INSERT INTO book_copies (id, status, book_id) VALUES (142, 'AVAILABLE', 36);
INSERT INTO book_copies (id, status, book_id) VALUES (143, 'BORROWED', 36);
INSERT INTO book_copies (id, status, book_id) VALUES (144, 'AVAILABLE', 36);
INSERT INTO book_copies (id, status, book_id) VALUES (145, 'AVAILABLE', 37);
INSERT INTO book_copies (id, status, book_id) VALUES (146, 'AVAILABLE', 37);
INSERT INTO book_copies (id, status, book_id) VALUES (147, 'BORROWED', 37);
INSERT INTO book_copies (id, status, book_id) VALUES (148, 'AVAILABLE', 37);
INSERT INTO book_copies (id, status, book_id) VALUES (149, 'AVAILABLE', 38);
INSERT INTO book_copies (id, status, book_id) VALUES (150, 'AVAILABLE', 38);
INSERT INTO book_copies (id, status, book_id) VALUES (151, 'BORROWED', 38);
INSERT INTO book_copies (id, status, book_id) VALUES (152, 'AVAILABLE', 38);
INSERT INTO book_copies (id, status, book_id) VALUES (153, 'AVAILABLE', 39);
INSERT INTO book_copies (id, status, book_id) VALUES (154, 'AVAILABLE', 39);
INSERT INTO book_copies (id, status, book_id) VALUES (155, 'BORROWED', 39);
INSERT INTO book_copies (id, status, book_id) VALUES (156, 'AVAILABLE', 39);
INSERT INTO book_copies (id, status, book_id) VALUES (157, 'AVAILABLE', 40);
INSERT INTO book_copies (id, status, book_id) VALUES (158, 'AVAILABLE', 40);
INSERT INTO book_copies (id, status, book_id) VALUES (159, 'BORROWED', 40);
INSERT INTO book_copies (id, status, book_id) VALUES (160, 'AVAILABLE', 40);
INSERT INTO book_copies (id, status, book_id) VALUES (161, 'AVAILABLE', 41);
INSERT INTO book_copies (id, status, book_id) VALUES (162, 'AVAILABLE', 41);
INSERT INTO book_copies (id, status, book_id) VALUES (163, 'BORROWED', 41);
INSERT INTO book_copies (id, status, book_id) VALUES (164, 'AVAILABLE', 41);
INSERT INTO book_copies (id, status, book_id) VALUES (165, 'AVAILABLE', 42);
INSERT INTO book_copies (id, status, book_id) VALUES (166, 'AVAILABLE', 42);
INSERT INTO book_copies (id, status, book_id) VALUES (167, 'BORROWED', 42);
INSERT INTO book_copies (id, status, book_id) VALUES (168, 'AVAILABLE', 42);
INSERT INTO book_copies (id, status, book_id) VALUES (169, 'AVAILABLE', 43);
INSERT INTO book_copies (id, status, book_id) VALUES (170, 'AVAILABLE', 43);
INSERT INTO book_copies (id, status, book_id) VALUES (171, 'BORROWED', 43);
INSERT INTO book_copies (id, status, book_id) VALUES (172, 'AVAILABLE', 43);
INSERT INTO book_copies (id, status, book_id) VALUES (173, 'AVAILABLE', 44);
INSERT INTO book_copies (id, status, book_id) VALUES (174, 'AVAILABLE', 44);
INSERT INTO book_copies (id, status, book_id) VALUES (175, 'BORROWED', 44);
INSERT INTO book_copies (id, status, book_id) VALUES (176, 'AVAILABLE', 44);
INSERT INTO book_copies (id, status, book_id) VALUES (177, 'AVAILABLE', 45);
INSERT INTO book_copies (id, status, book_id) VALUES (178, 'AVAILABLE', 45);
INSERT INTO book_copies (id, status, book_id) VALUES (179, 'BORROWED', 45);
INSERT INTO book_copies (id, status, book_id) VALUES (180, 'AVAILABLE', 45);
INSERT INTO book_copies (id, status, book_id) VALUES (181, 'AVAILABLE', 46);
INSERT INTO book_copies (id, status, book_id) VALUES (182, 'AVAILABLE', 46);
INSERT INTO book_copies (id, status, book_id) VALUES (183, 'BORROWED', 46);
INSERT INTO book_copies (id, status, book_id) VALUES (184, 'AVAILABLE', 46);
INSERT INTO book_copies (id, status, book_id) VALUES (185, 'AVAILABLE', 47);
INSERT INTO book_copies (id, status, book_id) VALUES (186, 'AVAILABLE', 47);
INSERT INTO book_copies (id, status, book_id) VALUES (187, 'BORROWED', 47);
INSERT INTO book_copies (id, status, book_id) VALUES (188, 'AVAILABLE', 47);
INSERT INTO book_copies (id, status, book_id) VALUES (189, 'AVAILABLE', 48);
INSERT INTO book_copies (id, status, book_id) VALUES (190, 'AVAILABLE', 48);
INSERT INTO book_copies (id, status, book_id) VALUES (191, 'BORROWED', 48);
INSERT INTO book_copies (id, status, book_id) VALUES (192, 'AVAILABLE', 48);
INSERT INTO book_copies (id, status, book_id) VALUES (193, 'AVAILABLE', 49);
INSERT INTO book_copies (id, status, book_id) VALUES (194, 'AVAILABLE', 49);
INSERT INTO book_copies (id, status, book_id) VALUES (195, 'BORROWED', 49);
INSERT INTO book_copies (id, status, book_id) VALUES (196, 'AVAILABLE', 49);
INSERT INTO book_copies (id, status, book_id) VALUES (197, 'AVAILABLE', 50);
INSERT INTO book_copies (id, status, book_id) VALUES (198, 'AVAILABLE', 50);
INSERT INTO book_copies (id, status, book_id) VALUES (199, 'BORROWED', 50);
INSERT INTO book_copies (id, status, book_id) VALUES (200, 'AVAILABLE', 50);